export const REQUEST_MOVIES_PENDING = 'REQUEST_MOVIES_PENDING'
export const REQUEST_MOVIES_SUCCESS = 'REQUEST_MOVIES_SUCCESS'
export const REQUEST_MOVIES_FAILED = 'REQUEST_MOVIES_FAILED'

export const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL'
export const GET_RENDER_DETAIL = 'GET_RENDER_DETAIL'

export const GET_SEARCH_INPUT = 'GET_SEARCH_INPUT'

export const REQUEST_SEARCH_PENDING = 'REQUEST_SEARCH_PENDING'
export const REQUEST_SEARCH_SUCCESS = 'REQUEST_SEARCH_SUCCESS'
export const REQUEST_SEARCH_FAILED = 'REQUEST_SEARCH_FAILED'

export const REQUEST_USER_PENDING = 'REQUEST_USER_PENDING'
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS'
export const REQUEST_USER_FAILED = 'REQUEST_USER_FAILED'
export const SAVE_USER_MOVIE = 'SAVE_USER_MOVIE'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const REMOVE_USER_MOVIE = 'REMOVE_USER_MOVIE'

