export const REQUEST_USER_PENDING = 'REQUEST_USER_PENDING'
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS'
export const REQUEST_USER_FAILED = 'REQUEST_USER_FAILED'
export const SAVE_USER_MOVIE = 'SAVE_USER_MOVIE'