export const REQUEST_CAST_DETAIL_PENDING = 'REQUEST_CAST_DETAIL_PENDING'
export const REQUEST_CAST_DETAIL_SUCCESS = 'REQUEST_CAST_DETAIL_SUCCESS'
export const REQUEST_CAST_DETAIL_FAILED = 'REQUEST_CAST_DETAIL_FAILED'