export const REQUEST_MOVIES_PENDING = 'REQUEST_MOVIES_PENDING'
export const REQUEST_MOVIES_SUCCESS = 'REQUEST_MOVIES_SUCCESS'
export const REQUEST_MOVIES_FAILED = 'REQUEST_MOVIES_FAILED'

export const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL'
