export const REQUEST_MOVIES_PENDING = 'REQUEST_MOVIES_PENDING'
export const REQUEST_MOVIES_SUCCESS = 'REQUEST_MOVIES_SUCCESS'
export const REQUEST_MOVIES_FAILED = 'REQUEST_MOVIES_FAILED'

export const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL'

export const REQUEST_DETAIL_PENDING = 'REQUEST_DETAIL_PENDING'
export const REQUEST_DETAIL_SUCCESS = 'REQUEST_DETAIL_SUCCESS'
export const REQUEST_DETAIL_FAILED = 'REQUEST_DETAIL_FAILED'